# Generated by Django 6.0.4 on 2026-04-22 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("status", models.BooleanField(default=False)),
                ("category", models.TextField(blank=True, max_length=100, null=True)),
                ("number_of_repetitions", models.PositiveIntegerField()),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("best_streak", models.PositiveIntegerField(default=0)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("last_completed", models.DateField(blank=True, null=True)),
                (
                    "interval_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("WEEKDAYS", "Weekdays"),
                            ("WEEKENDS", "Weekends"),
                            ("CUSTOM_DAYS", "Custom Days"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
