# Generated by Django 6.0.4 on 2026-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="number_of_repetitions",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
