# Generated by Django 6.0.4 on 2026-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="overdue",
            field=models.BooleanField(default=False),
        ),
    ]
